version: "3"
services:

  speckle-frontend:
    build:
      context: .
      dockerfile: packages/frontend/Dockerfile
    restart: always

  speckle-server:
    build:
      context: .
      dockerfile: packages/server/Dockerfile
      args:
        NODE_ENV: development
    restart: always
    environment:
      CANONICAL_URL: "http://localhost:3000"
      SESSION_SECRET: "-local-"
      STRATEGY_LOCAL: "true"
      DEBUG: "speckle:*"
      FRONTEND_HOST: "speckle-frontend"
      FRONTEND_PORT: 80

      POSTGRES_URL: "postgres"
      POSTGRES_USER: "speckle"
      POSTGRES_PASSWORD: "speckle"
      POSTGRES_DB: "speckle"

      REDIS_URL: "redis://redis"
    ports:
      - "127.0.0.1:3000:3000"
