version: "3"
services:

  speckle-frontend:
    build:
      context: .
      dockerfile: packages/frontend/Dockerfile
    restart: always
    ports:
      - "0.0.0.0:80:80"

  speckle-server:
    build:
      context: .
      dockerfile: packages/server/Dockerfile
    restart: always
    environment:
      # TODO: Change this to the URL of the speckle server, as accessed from the network
      CANONICAL_URL: "http://localhost"

      # TODO: Change this to a unique secret for this server
      SESSION_SECRET: "TODO:Replace"

      STRATEGY_LOCAL: "true"
      DEBUG: "speckle:*"

      POSTGRES_URL: "postgres"
      POSTGRES_USER: "speckle"
      POSTGRES_PASSWORD: "speckle"
      POSTGRES_DB: "speckle"

      REDIS_URL: "redis://redis"
